<h3>Adicionar Funcionário</h3>

<form method="post">
	Informe o nome do funcionário:
	<br>
	<input type="text" name="nome">
	<br><br>
	Informe o CPF do funcionário:
	<br>
	<input type="text" name="cpf">
	<br><br>
	Informe o salário do funcionário:
	<br>
	<input type="text" name="salario">
	<br><br>
	<input type="submit" value="Adicionar">
</form>

<br><br>

<?php
	// Exibe mensagens sobre a página.
	echo $this->msg;
?>